import React, { useEffect } from 'react';
import { FileText, Mail, Scale, AlertTriangle, CreditCard, Shield, Users, Gavel } from 'lucide-react';
import SmokeyCursor from './ui/SmokeyCursor';
import { ModernHeader } from './ui/modern-header';
import { Footer } from './ui/Footer';

const TermsOfService: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const sections = [
    {
      icon: Users,
      title: "Acceptance of Terms",
      content: [
        {
          subtitle: "Agreement to Terms",
          text: "By accessing and using Brushly's services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services."
        },
        {
          subtitle: "Eligibility",
          text: "You must be at least 18 years old to use our services. By using Brushly, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these terms."
        },
        {
          subtitle: "Account Registration",
          text: "To access certain features, you must create an account with accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
        }
      ]
    },
    {
      icon: Shield,
      title: "Service Description",
      content: [
        {
          subtitle: "AI-Powered Content Generation",
          text: "Brushly provides AI-powered tools for generating marketing content, social media posts, and promotional materials for artists and creators. Our services include content generation, social media integration, and artwork management features."
        },
        {
          subtitle: "Beta Services",
          text: "Some features may be offered as beta or preview services. These features are provided 'as is' and may contain bugs or limitations. We reserve the right to modify or discontinue beta features at any time."
        },
        {
          subtitle: "Service Availability",
          text: "We strive to maintain high service availability but do not guarantee uninterrupted access. Services may be temporarily unavailable due to maintenance, updates, or technical issues."
        }
      ]
    },
    {
      icon: FileText,
      title: "User Content and Rights",
      content: [
        {
          subtitle: "Your Content",
          text: "You retain ownership of all artwork, images, and content you upload to Brushly. By uploading content, you grant us a limited license to process, store, and use your content solely to provide our services."
        },
        {
          subtitle: "Generated Content",
          text: "Content generated by our AI tools based on your input is provided for your use. However, you are responsible for ensuring that any generated content complies with applicable laws and platform policies before publication."
        },
        {
          subtitle: "Content Guidelines",
          text: "You agree not to upload or generate content that is illegal, harmful, threatening, abusive, defamatory, or violates intellectual property rights. We reserve the right to remove content that violates these guidelines."
        }
      ]
    },
    {
      icon: CreditCard,
      title: "Payment and Billing",
      content: [
        {
          subtitle: "Subscription Plans",
          text: "Brushly offers various subscription plans with different features and usage limits. Subscription fees are billed in advance on a monthly or annual basis, depending on your chosen plan."
        },
        {
          subtitle: "Payment Processing",
          text: "Payments are processed through secure third-party payment processors. You agree to provide accurate payment information and authorize us to charge your payment method for applicable fees."
        },
        {
          subtitle: "Refunds and Cancellation",
          text: "You may cancel your subscription at any time through your account settings. Refunds are generally not provided for partial billing periods, but we may offer refunds at our discretion for technical issues or service failures."
        }
      ]
    },
    {
      icon: AlertTriangle,
      title: "Prohibited Uses",
      content: [
        {
          subtitle: "Illegal Activities",
          text: "You may not use our services for any illegal purposes or to violate any laws in your jurisdiction. This includes but is not limited to copyright infringement, fraud, or harassment."
        },
        {
          subtitle: "System Abuse",
          text: "You may not attempt to gain unauthorized access to our systems, interfere with service operation, or use automated tools to access our services beyond normal usage patterns."
        },
        {
          subtitle: "Commercial Restrictions",
          text: "You may not resell, redistribute, or create derivative services based on Brushly without explicit written permission. Our services are licensed for your personal or business use only."
        }
      ]
    },
    {
      icon: Scale,
      title: "Limitation of Liability",
      content: [
        {
          subtitle: "Service Disclaimer",
          text: "Our services are provided 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of AI-generated content or service availability."
        },
        {
          subtitle: "Liability Limits",
          text: "To the maximum extent permitted by law, our total liability for any claims related to our services shall not exceed the amount you paid for services in the 12 months preceding the claim."
        },
        {
          subtitle: "Indirect Damages",
          text: "We shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities."
        }
      ]
    },
    {
      icon: Gavel,
      title: "Dispute Resolution",
      content: [
        {
          subtitle: "Governing Law",
          text: "These terms shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflict of law provisions."
        },
        {
          subtitle: "Arbitration",
          text: "Any disputes arising from these terms or our services shall be resolved through binding arbitration rather than in court, except for claims that may be brought in small claims court."
        },
        {
          subtitle: "Class Action Waiver",
          text: "You agree to resolve disputes individually and waive any right to participate in class action lawsuits or class-wide arbitration against Brushly."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700 relative overflow-hidden">
      {/* Smokey Cursor Effect - KEEPING UNTOUCHED */}
      <SmokeyCursor 
        simulationResolution={256}
        dyeResolution={1024}
        densityDissipation={0.98}
        velocityDissipation={0.99}
        pressure={0.8}
        curl={30}
        splatRadius={0.25}
        splatForce={6000}
        backgroundColor={{ r: 0.1, g: 0.1, b: 0.15 }}
        transparent={true}
        intensity={0.8}
      />

      {/* Main Content */}
      <div className="relative z-10">
        <ModernHeader />
        
        <div className="pt-24">
        {/* Hero Section */}
        <section className="py-20 px-6">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12 animate-fade-in">

              <div className="inline-flex items-center space-x-3 bg-gradient-to-r from-amber-500/20 to-orange-400/20 border border-amber-500/30 rounded-full px-8 py-4 mb-8">
                <FileText className="w-6 h-6 text-amber-400" />
                <span className="text-amber-300 font-bold text-lg">Terms of Service</span>
              </div>

              <h1 className="text-5xl lg:text-6xl font-bold mb-8 leading-tight">
                <span className="text-slate-200">Terms of</span>
                <br />
                <span className="bg-gradient-to-r from-amber-400 via-orange-300 to-red-400 bg-clip-text text-transparent">
                  Service
                </span>
              </h1>

              <p className="text-xl text-slate-300 leading-relaxed max-w-3xl mx-auto">
                These terms govern your use of Brushly's AI-powered creative tools and services. 
                Please read them carefully to understand your rights and responsibilities.
              </p>

              <div className="mt-8 text-sm text-slate-400">
                <p>Last updated: October 1, 2025</p>
              </div>
            </div>
          </div>
        </section>

        {/* Terms Content */}
        <section className="py-12 px-6">
          <div className="max-w-4xl mx-auto">
            {sections.map((section, index) => {
              const Icon = section.icon;
              return (
                <div
                  key={index}
                  className="mb-16 animate-fade-in"
                  style={{ animationDelay: `${index * 0.1}s` }}
                >
                  <div className="bg-slate-800/40 backdrop-blur-xl rounded-2xl border border-slate-700/50 p-8 shadow-xl">
                    {/* Section Header */}
                    <div className="flex items-center space-x-4 mb-8">
                      <div className="w-12 h-12 bg-gradient-to-r from-amber-500 to-orange-400 rounded-xl flex items-center justify-center shadow-lg">
                        <Icon className="w-6 h-6 text-white" />
                      </div>
                      <h2 className="text-2xl font-bold text-slate-200">{section.title}</h2>
                    </div>

                    {/* Section Content */}
                    <div className="space-y-6">
                      {section.content.map((item, itemIndex) => (
                        <div key={itemIndex} className="border-l-2 border-slate-600/50 pl-6">
                          <h3 className="text-lg font-semibold text-slate-200 mb-3">
                            {item.subtitle}
                          </h3>
                          <p className="text-slate-300 leading-relaxed">
                            {item.text}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              );
            })}

            {/* Contact Information */}
            <div className="bg-slate-800/40 backdrop-blur-xl rounded-2xl border border-slate-700/50 p-8 shadow-xl">
              <div className="flex items-center space-x-4 mb-6">
                <div className="w-12 h-12 bg-gradient-to-r from-teal-500 to-cyan-400 rounded-xl flex items-center justify-center shadow-lg">
                  <Mail className="w-6 h-6 text-white" />
                </div>
                <h2 className="text-2xl font-bold text-slate-200">Questions About These Terms?</h2>
              </div>

              <div className="space-y-4">
                <p className="text-slate-300 leading-relaxed">
                  If you have any questions about these Terms of Service or need clarification 
                  on any provisions, please contact us:
                </p>
                
                <div className="bg-slate-700/30 rounded-lg p-4 border border-slate-600/30">
                  <p className="text-slate-200 font-medium">Email: legal@brushly.ai</p>
                  <p className="text-slate-300 text-sm mt-2">
                    Our legal team will respond to your inquiry within 48 hours during business days.
                  </p>
                </div>
              </div>
            </div>

            {/* Terms Updates */}
            <div className="mt-12 bg-gradient-to-r from-amber-500/10 to-orange-400/10 border border-amber-500/20 rounded-2xl p-6 animate-fade-in">
              <h3 className="text-lg font-semibold text-slate-200 mb-3">
                Changes to These Terms
              </h3>
              <p className="text-slate-300 leading-relaxed">
                We reserve the right to modify these Terms of Service at any time. We will notify users 
                of any material changes by email and by posting the updated terms on our website. 
                Continued use of our services after changes become effective constitutes acceptance of the new terms.
              </p>
            </div>

            {/* Effective Date */}
            <div className="mt-8 text-center bg-slate-800/20 rounded-lg p-4 border border-slate-700/30 animate-fade-in">
              <p className="text-slate-400 text-sm">
                These Terms of Service are effective as of October 1, 2025, and apply to all users of Brushly's services.
              </p>
            </div>
          </div>
        </section>
        
        <Footer currentPage="terms" />
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
